#! /bin/bash

# 1. Teste da quantidade  de parâmetros passados pelo usuário pelo "$#" sendo menor ou igual à 2
if [ "$#" -lt 2 ]; then
	echo "O programa $0 requer nome do arquivo e arquivos a serem compactados"
	exit 1
fi

# 2. Variável com o nome do arquivo de saída captando o primeiro parâmetro
arquivo_saida="$1"

# 3. Variável com um array contendo os demais parâmetros a partir do segundo
arquivos=("${@:2}")

# 4. Execução do programa
tar -czf "$arquivo_saida" "${arquivos[@]}"
echo "Compactado com sucesso em $arquivo_saida"
